import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://demo.playwright.dev/todomvc/#/")
    page.get_by_role("textbox", name="What needs to be done?").click()
    page.get_by_role("textbox", name="What needs to be done?").fill("here si an action item")
    page.get_by_role("textbox", name="What needs to be done?").press("Enter")
    page.get_by_role("textbox", name="What needs to be done?").click()
    page.get_by_role("textbox", name="What needs to be done?").click()
    page.get_by_role("textbox", name="What needs to be done?").fill("resumed recording")
    page.get_by_role("textbox", name="What needs to be done?").click()
    page.get_by_role("link", name="Active").click()
    page.get_by_role("link", name="All").click()
    page.get_by_role("textbox", name="What needs to be done?").click()
    page.get_by_test_id("todo-title").click()
    page.get_by_role("textbox", name="What needs to be done?").click()
    page.get_by_role("textbox", name="What needs to be done?").fill("")
    page1 = context.new_page()
    page1.goto("https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Dthis%2Bis%2Ba%2Bnew%2Bpage%26oq%3Dthis%2Bis%2Ba%2Bnew%2Bpage%2B%26gs_lcrp%3DEgZjaHJvbWUyBggAEEUYOdIBCDU0NzdqMGoxqAIAsAIA%26sourceid%3Dchrome%26ie%3DUTF-8%26sei%3D9azQZ9mCDMKu0PEPtrD1gA4&q=EhAmB_bQAA01dAAAAAAAAAHLGPXZwr4GIjDZgYotVunf3MAVCllRP-itwIQKYEjydbPNQpuFt1o6hfkf7BnHI8JpB4dwI_dDeuoyAXJaAUM")
    page1.locator("body").click()
    page1.locator("iframe[name=\"a-ourxuhdev5r6\"]").content_frame.get_by_role("checkbox", name="I'm not a robot").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(3) > td").first.click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(3) > td:nth-child(2)").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(2) > td:nth-child(3)").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(2) > td:nth-child(2)").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(3) > td:nth-child(3)").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(3) > td:nth-child(4)").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(2) > td:nth-child(4)").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(4) > td").first.click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(4) > td:nth-child(2)").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.get_by_role("button", name="Next").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(4) > td").first.click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(4) > td:nth-child(2)").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(4) > td:nth-child(3)").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(4) > td:nth-child(4)").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(3) > td:nth-child(3)").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(3) > td:nth-child(2)").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(3) > td").first.click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.get_by_role("button", name="Next").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(2) > td:nth-child(3)").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("td:nth-child(3)").first.click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("div").filter(has_text=re.compile(r"^Next$")).nth(2).click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.get_by_role("button", name="Next").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(3) > td:nth-child(2)").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(2) > td:nth-child(3)").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(3) > td:nth-child(3)").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(2) > td:nth-child(2)").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(2) > td:nth-child(2)").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(3) > td").first.click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.get_by_role("button", name="Next").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(2) > td:nth-child(3)").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(3) > td:nth-child(2)").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(3) > td:nth-child(3)").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(2) > td:nth-child(4)").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("td:nth-child(4)").first.click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("td:nth-child(3)").first.click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(3) > td:nth-child(4)").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.get_by_role("button", name="Verify").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(2) > td").first.click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(3) > td").first.click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(3) > td:nth-child(3)").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.locator("tr:nth-child(3) > td:nth-child(3)").click()
    page1.locator("iframe[name=\"c-ourxuhdev5r6\"]").content_frame.get_by_role("button", name="Verify").click()
    page1.get_by_role("link", name="Create New Page National Park").click()
    page1.get_by_text("Open topic with navigation You are here: Contributors Reference > CommonSpot").click()
    page1.goto("https://www.nps.gov/commonspot/help/content/contributors_reference/create_new_page.htm")
    page1.get_by_role("link", name="Open topic with navigation").first.click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
